### ISSUE TITLE
Pause/Unpause mouse using a keyboard shortcut

### ISSUE THREAD

**Issue by smokyabdulrahman** [GilgameshxZero/kb-as-mouse#1]
Thank you for this amazing solution.

I am finding it difficulty to siwtch the application on and off again so that i able able to write proparly again.
I would love to work on adding the feature of "Pause/Unpause" using a keyboard shortcut. Please, guide me to where i should write that logic.

Thank you again.

**Comment by GilgameshxZero** [comment]
Hey @smokyabdulrahman, the default pause/unpause button is the “context menu” button, which looks like this:

![image](https://user-images.githubusercontent.com/20709601/157922246-a5543ca8-b3d9-43ea-baf9-4ae9bf90d49e.png)

You can change the button for pause/unpause by creating a shortcut to the application in Windows, and adding parameters to the “Target:” line. For example, you can add `--help`, and run the shortcut, to see all the options available:

![image](https://user-images.githubusercontent.com/20709601/157922644-96d75c8e-8969-4b6c-8471-e62d291a6a02.png)

![image](https://user-images.githubusercontent.com/20709601/157923001-68c48fde-2e2f-4ef5-b1ea-f24b29c72e9d.png)

For example, if you wanted to use F8 as the pause/unpause key, you would add `--pause 119`. 119 is 0x77 in decimal. You can find a list of the key codes [here](https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes).

Let me know if this helps! Happy to discuss features if you think there’s a better way to do this.

**Comment by smokyabdulrahman** [comment]
Wow, thank you! That works really great. I just tested it. I think I haven’t read the docs properly, that’s my bad. If i have any other issues or features i will be contacting you instantly. 
Thanks a lot!
